# Generate a helper that registers every thrift-c_glib GType up front, once,
# under a thread-safe guard.
#
# thrift's generated get_type() functions use a racy "if (type == 0)
# g_type_register_static(...)" pattern. The first *concurrent* Hive/Impala use
# then hits "GLib-GObject-CRITICAL: cannot register existing type". Calling every
# get_type() once from a single thread (g_once) before any concurrency removes
# the race. Each TYPE_T_* macro expands to its get_type() call, so referencing
# them all is enough — no instances are created.
#
# Usage: cmake -DHEADER=<types.h> -DOUT=<argus_thrift_prime.c> -P gen_prime.cmake

file(STRINGS "${HEADER}" _lines REGEX "^#define TYPE_T_[A-Z0-9_]+ ")
set(_calls "")
foreach(_line IN LISTS _lines)
    if(_line MATCHES "^#define (TYPE_T_[A-Z0-9_]+) ")
        set(_calls "${_calls}    (void)${CMAKE_MATCH_1};\n")
    endif()
endforeach()

file(WRITE "${OUT}"
"/* Generated by gen_prime.cmake — do not edit. */
#include <glib-object.h>
#include \"t_c_l_i_service_types.h\"
#include \"argus_thrift_prime.h\"

void argus_thrift_prime_types(void)
{
    static gsize done = 0;
    if (g_once_init_enter(&done)) {
${_calls}        g_once_init_leave(&done, 1);
    }
}
")

get_filename_component(_dir "${OUT}" DIRECTORY)
file(WRITE "${_dir}/argus_thrift_prime.h"
"/* Generated by gen_prime.cmake — do not edit. */
#ifndef ARGUS_THRIFT_PRIME_H
#define ARGUS_THRIFT_PRIME_H
/* Register all thrift-c_glib types once, thread-safely, before concurrent use. */
void argus_thrift_prime_types(void);
#endif
")
