-- TDVT test tables (TestV1: Calcs + Staples), typed for Trino.
--
-- Target: the built-in `memory` connector — writable, no object store, perfect
-- for a TDVT run. Enable it once by adding, in the Trino coordinator,
--   etc/catalog/memory.properties  →  connector.name=memory
-- (the trinodb/trino image: mount or exec-write that file, then restart), then:
--   trino> CREATE SCHEMA IF NOT EXISTS memory.tdvt;
-- and run this DDL. load.py then fills the tables from the SDK CSVs.
--
-- Type mapping from the generic TestV1 DDL: DOUBLE PRECISION→DOUBLE,
-- NUMERIC(18,4)→DECIMAL(18,4); the rest are identical to Trino's names.

CREATE TABLE IF NOT EXISTS memory.tdvt."Calcs" (
    "key"       VARCHAR(255),
    "num0"      DOUBLE,
    "num1"      DOUBLE,
    "num2"      DOUBLE,
    "num3"      DOUBLE,
    "num4"      DOUBLE,
    "str0"      VARCHAR(255),
    "str1"      VARCHAR(255),
    "str2"      VARCHAR(255),
    "str3"      VARCHAR(255),
    "int0"      INTEGER,
    "int1"      INTEGER,
    "int2"      INTEGER,
    "int3"      INTEGER,
    "bool0"     BOOLEAN,
    "bool1"     BOOLEAN,
    "bool2"     BOOLEAN,
    "bool3"     BOOLEAN,
    "date0"     DATE,
    "date1"     DATE,
    "date2"     DATE,
    "date3"     DATE,
    "time0"     TIMESTAMP,
    "time1"     TIME,
    "datetime0" TIMESTAMP,
    "datetime1" VARCHAR(255),
    "zzz"       VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS memory.tdvt."Staples" (
    "Item Count"          INTEGER,
    "Ship Priority"       VARCHAR(14),
    "Order Priority"      VARCHAR(15),
    "Order Status"        VARCHAR(13),
    "Order Quantity"      DOUBLE,
    "Sales Total"         DOUBLE,
    "Discount"            DOUBLE,
    "Tax Rate"            DOUBLE,
    "Ship Mode"           VARCHAR(25),
    "Fill Time"           DOUBLE,
    "Gross Profit"        DOUBLE,
    "Price"               DECIMAL(18,4),
    "Ship Handle Cost"    DECIMAL(18,4),
    "Employee Name"       VARCHAR(50),
    "Employee Dept"       VARCHAR(4),
    "Manager Name"        VARCHAR(255),
    "Employee Yrs Exp"    DOUBLE,
    "Employee Salary"     DECIMAL(18,4),
    "Customer Name"       VARCHAR(50),
    "Customer State"      VARCHAR(50),
    "Call Center Region"  VARCHAR(25),
    "Customer Balance"    DOUBLE,
    "Customer Segment"    VARCHAR(25),
    "Prod Type1"          VARCHAR(50),
    "Prod Type2"          VARCHAR(50),
    "Prod Type3"          VARCHAR(50),
    "Prod Type4"          VARCHAR(50),
    "Product Name"        VARCHAR(100),
    "Product Container"   VARCHAR(25),
    "Ship Promo"          VARCHAR(25),
    "Supplier Name"       VARCHAR(25),
    "Supplier Balance"    DOUBLE,
    "Supplier Region"     VARCHAR(25),
    "Supplier State"      VARCHAR(50),
    "Order ID"            VARCHAR(10),
    "Order Year"          INTEGER,
    "Order Month"         INTEGER,
    "Order Day"           INTEGER,
    "Order Date"          TIMESTAMP,
    "Order Quarter"       VARCHAR(2),
    "Product Base Margin" DOUBLE,
    "Product ID"          VARCHAR(5),
    "Receive Time"        DOUBLE,
    "Received Date"       TIMESTAMP,
    "Ship Date"           TIMESTAMP,
    "Ship Charge"         DECIMAL(18,4),
    "Total Cycle Time"    DOUBLE,
    "Product In Stock"    VARCHAR(3),
    "PID"                 INTEGER,
    "Market Segment"      VARCHAR(25)
);
